# Production Internal Users Configuration
# Generated on: Fri Aug 22 18:19:43 EEST 2025

_meta:
  type: "internalusers"
  config_version: 2

# Admin user (for cluster administration)
admin:
  hash: "$2b$12$U97LL7QeoFI3E2rIiL23z.KCni10Lnx3RIcO3pnr/KRtB78wBfk9K"
  reserved: true
  backend_roles:
  - "admin"
  description: "Admin user for cluster management"

# Kibana server user (for Dashboards communication)
kibanaserver:
  hash: "$2b$12$pHpPCWLi6tgXP1B85Ly3BO4d0Ls4ZRgf9otcNFyIUN5koEeuC8voe"
  reserved: true
  description: "Kibana server user"

# GovDoc ingestion user (for application data ingestion)
govdoc_ingest:
  hash: "$2b$12$xbD9QdZDhnxd/N.n8gQUEO/8f3xnxS6Dlyde4HkTF8kqqAs32f9SW"
  reserved: false
  backend_roles: []
  description: "GovDoc application user for data ingestion"
  attributes:
    created_by: "production-setup"
    purpose: "data-ingestion"
