# Production Internal Users Configuration
# Generated on: Fri Aug 22 17:12:05 EEST 2025

_meta:
  type: "internalusers"
  config_version: 2

# Admin user (for cluster administration)
admin:
  hash: "$2b$12$WGSWFRa.UuqHaE2HFlEFEuI6EN7sPMYWE5TzLC8vEStCss0hgfw8K"
  reserved: true
  backend_roles:
  - "admin"
  description: "Admin user for cluster management"

# Kibana server user (for Dashboards communication)
kibanaserver:
  hash: "$2b$12$efbhpKzc9kCgSjRqCqQY5uq2tDwbqnl.dXPAOtZJ20UpbrKq2G0Ta"
  reserved: true
  description: "Kibana server user"

# GovDoc ingestion user (for application data ingestion)
govdoc_ingest:
  hash: "$2b$12$9ZA0zhu3BCeOuVdzekfGye1XqOivEnrxY.lnJmH46foSb1q2KxPie"
  reserved: false
  backend_roles: []
  description: "GovDoc application user for data ingestion"
  attributes:
    created_by: "production-setup"
    purpose: "data-ingestion"
