# Production Internal Users Configuration
# Generated on: Sat Aug 23 14:45:09 EEST 2025

_meta:
  type: "internalusers"
  config_version: 2

# Admin user (for cluster administration)
admin:
  hash: "$2b$12$r/LCiX95ij8QHvDcMdo/SeS9M6sirEAW7MCqOce3MX9Org09bm0SK"
  reserved: true
  backend_roles:
    - "admin"
  description: "Admin user for cluster management"

# Kibana server user (for Dashboards communication)
kibanaserver:
  hash: "$2b$12$HtS4KZ.x3kkkpJ/rgqOzJu6gczk3FPBaN4i6Ca088yr23Pw0crfH2"
  reserved: true
  description: "Kibana server user"

# GovDoc ingestion user (for application data ingestion)
govdoc_ingest:
  hash: "$2b$12$QAxi0s3yibl4TwsB3cs0W.XaXF8Sy4WTok6zIA6CKHIb8LtHUNy9O"
  reserved: false
  backend_roles: []
  description: "GovDoc application user for data ingestion"
  attributes:
    created_by: "production-setup"
    purpose: "data-ingestion"
