# Production Roles Configuration
# Generated on: Fri Aug 22 17:12:05 EEST 2025

_meta:
  type: "roles"
  config_version: 2

# GovDoc ingestion role - minimal permissions for data ingestion
govdoc_ingest_role:
  reserved: false
  cluster_permissions:
  - "indices:admin/create"
  - "cluster:admin/aliases"
  - "cluster:monitor/health"
  - "cluster:monitor/stats"
  index_permissions:
  - index_patterns:
    - "govdoc-companies-*"
    allowed_actions:
    - "indices:data/write/index"
    - "indices:data/write/bulk"
    - "indices:data/write/update"
    - "indices:data/write/delete"
    - "indices:admin/refresh"
    - "indices:admin/mapping/put"
    - "indices:admin/rollover"
    - "indices:data/read/search"
    - "indices:data/read/get"
  description: "Role for GovDoc application data ingestion"

# Read-only role for queries (future use)
govdoc_read_role:
  reserved: false
  cluster_permissions:
  - "cluster:monitor/health"
  - "cluster:monitor/stats"
  index_permissions:
  - index_patterns:
    - "govdoc-companies-*"
    allowed_actions:
    - "indices:data/read/search"
    - "indices:data/read/get"
    - "indices:data/read/scroll"
  description: "Read-only role for GovDoc queries"
